language: julia

sudo: required

dist: trusty

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - nightly

matrix:
  allow_failures:
    - julia: nightly

env:
  - MPI_IMPL=mpich
  - MPI_IMPL=openmpi

before_install:
  - sh ./deps/travis-install-mpi.sh $MPI_IMPL
  - export PATH=$HOME/OpenMPI/bin:$PATH

## uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Hypre"); Pkg.test("Hypre"; coverage=true)'

after_success:
  # push coverage results to Codecov
  - julia -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(Codecov.process_folder())"