language: julia
os:
    - osx
    - linux
julia:
    - 0.4
    - nightly
matrix:
    allow_failures:
      - julia: nightly
notifications:
    email: false
    slack: fit-pde:LzLEcCWinA1d9YPSsN4GnTL1
addons:
  apt:
    packages:
    - gfortran
    - cmake
    - mpich2
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Hypre"); Pkg.test("Hypre"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("Hypre")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';